[package]
name = "ipc-pair"
version = "0.1.0"
edition = "2018"

[lib]
name = "kv_ipc_client"
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
